# Generated by Django 3.1.1 on 2020-09-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_genre_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
