# Generated by Django 3.1.1 on 2020-09-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='dimensions',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(upload_to='book/img'),
        ),
    ]
