# Generated by Django 3.1.1 on 2020-09-15 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20200914_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='IdSeries',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.series'),
        ),
    ]
