# Generated by Django 3.1.1 on 2020-09-15 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20200915_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='IdPublisher',
            new_name='Publisher',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='IdSeries',
            new_name='Series',
        ),
        migrations.AlterModelTable(
            name='author',
            table='book_author',
        ),
        migrations.AlterModelTable(
            name='genre',
            table='book_genre',
        ),
        migrations.AlterModelTable(
            name='publisher',
            table='book_publisher',
        ),
        migrations.AlterModelTable(
            name='series',
            table='book_series',
        ),
    ]
