# Generated by Django 3.1.1 on 2020-09-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_auto_20200917_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Genre',
            field=models.ManyToManyField(to='book.genre'),
        ),
    ]
