# Generated by Django 3.1.1 on 2020-09-17 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_book_genre'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='genre',
            table='genre-Book',
        ),
    ]
