# Generated by Django 3.1.1 on 2020-09-17 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_auto_20200917_2250'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='book-author',
        ),
        migrations.AlterModelTable(
            name='genre',
            table='book-genre',
        ),
        migrations.AlterModelTable(
            name='publisher',
            table='book-publisher',
        ),
        migrations.AlterModelTable(
            name='series',
            table='book-series',
        ),
    ]
