# Generated by Django 3.1.1 on 2020-09-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_auto_20200917_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Author',
            field=models.ManyToManyField(to='book.author'),
        ),
    ]
