# Generated by Django 3.1.1 on 2020-09-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Editor',
            field=models.ManyToManyField(db_table='book_editor', to='book.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='Author',
            field=models.ManyToManyField(related_name='author', to='book.author'),
        ),
    ]
