# Generated by Django 3.1.1 on 2020-09-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0018_auto_20200919_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Author',
            field=models.ManyToManyField(related_name='Author', to='book.author', verbose_name='Автор книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='Editor',
            field=models.ManyToManyField(db_table='book_editor', related_name='Editor', to='book.author', verbose_name='Переводчик книги'),
        ),
    ]
